### PR TITLE
making changes to schedule to match ClassTranscribe

### PR DESCRIPTION
**Pull request by devanshipratap**
I've moved some stuff around to match ClassTranscribe as closely as possible. The numbering doesn't exactly line up because I think lectures used the same handout for multiple days; the CT videos are less than the number of lectures. I wasn't sure how to see the preview for this schedule, so not sure what it might look like. Color scheming was another question - I haven't changed it, but I can change it depending on what we want.

### CODE REVIEW

**Comment by PradyumnaShome** [comment]
This looks good. I'm just wondering what students are going to do in the last few weeks
image

**Comment by devanshipratap** [comment]
@PradyumnaShome Yeah, I'm not sure either, but since Prof. Angrave said that it's okay to have less lectures, I'm assuming it should be fine. I also think it gives students some sort of a buffer if they do fall behind on CT lectures.

**Comment by MaciejKrzysiak** [comment]
Are we deploying this?

**Comment by ayushr2** [comment]
We should!

**Pull request merged**
