### PR TITLE
Update 404 error image

### PR DESCRIPTION
**Pull request by MaciejKrzysiak**

### CODE REVIEW

**Comment by PradyumnaShome** [comment]
@MaciejKrzysiak Screenshot?

**Comment by MaciejKrzysiak** [comment]
> @MaciejKrzysiak Screenshot?

Huh?

**Comment by PradyumnaShome** [comment]
May I have a look at a screenshot?

**Comment by MaciejKrzysiak** [comment]
[Website 404 image error](https://trello.com/c/G3kioAUO/19-website-404-image-error)

**Comment by MaciejKrzysiak** [comment]
> May I have a look at a screenshot of the 404 page? Please include a screenshot in all web changes :)

That took forever,
Screen Shot 2020-02-03 at 9 23 55 PM

**Pull request merged**
