### PR TITLE
Updated schedule.md

### PR DESCRIPTION
**Pull request by MaciejKrzysiak**
Updated schedule.md with lab/mp due dates and quiz times.

### CODE REVIEW

**Comment by rafilong** [comment]
What are your thoughts about having a table rather than a bulleted list?

**Comment by MaciejKrzysiak** [comment]
> What are your thoughts about having a table rather than a bulleted list?

For all the data? Or a table of deadlines?

**Comment by rafilong** [comment]
I would say all of the data, though the final decision is up to you. For me, it makes sense for this type of data to be in a table. I would have a column for date, and then maybe separate columns for deadline, exam, etc.

**Comment by MaciejKrzysiak** [comment]
> I would say all of the data, though the final decision is up to you. For me, it makes sense for this type of data to be in a table. I would have a column for date, and then maybe separate columns for deadline, exam, etc.

I think it makes sense for it to be linear, like the days of the week. I tried the table and since most days have lecture, lab, or mp and not multiple things going on the table is pretty scarce.I also don't really want to mess with Angrave's week 1 style.

**Comment by rafilong** [comment]
That's fair, my critique was more of a question of personal design. I just felt like it would be easier to isolate information that you're searching for if separated into a table.

About actionable feedback - aren't labs released on Wednesdays now?

**Comment by MaciejKrzysiak** [comment]
> That's fair, my critique was more of a question of personal design. I just felt like it would be easier to isolate information that you're searching for if separated into a table.
> 
> About actionable feedback - aren't labs released on Wednesdays now?

Ahh yes, I've updated labs to being assigned on Wednesdays. I also noted that Weds/Thurs have lab.

**Comment by rafilong** [comment]
LGTM

**Pull request merged**
